//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritoryWeb.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Territories.
        /// </summary>
        public static string Dash1Link {
            get {
                return ResourceManager.GetString("Dash1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Doors Added.
        /// </summary>
        public static string Dash1Title {
            get {
                return ResourceManager.GetString("Dash1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Territories.
        /// </summary>
        public static string Dash2Link {
            get {
                return ResourceManager.GetString("Dash2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked-in Territory.
        /// </summary>
        public static string Dash2Title {
            get {
                return ResourceManager.GetString("Dash2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Territories.
        /// </summary>
        public static string Dash3Link {
            get {
                return ResourceManager.GetString("Dash3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors Modified.
        /// </summary>
        public static string Dash3Title {
            get {
                return ResourceManager.GetString("Dash3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked In.
        /// </summary>
        public static string DashHeaderCheckedIn {
            get {
                return ResourceManager.GetString("DashHeaderCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DashHeaderCount {
            get {
                return ResourceManager.GetString("DashHeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Added.
        /// </summary>
        public static string DashHeaderLastAdded {
            get {
                return ResourceManager.GetString("DashHeaderLastAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string DashHeaderLastModified {
            get {
                return ResourceManager.GetString("DashHeaderLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string DashHeaderTerritory {
            get {
                return ResourceManager.GetString("DashHeaderTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view territory details..
        /// </summary>
        public static string TerritoryButtonTitle {
            get {
                return ResourceManager.GetString("TerritoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Feature.
        /// </summary>
        public static string WelcomeLink {
            get {
                return ResourceManager.GetString("WelcomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will help you better manage the territories in your congregation. The information is stored securely. No one besides people in your congregation will have access to this information. So, please make sure you use the export feature regularly to keep a backup of the data in the congregation..
        /// </summary>
        public static string WelcomeParagraph {
            get {
                return ResourceManager.GetString("WelcomeParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Territory Web.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
