//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Doors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritoryWeb.Resources.Views.Doors.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Door.
        /// </summary>
        public static string AddDoorBtn {
            get {
                return ResourceManager.GetString("AddDoorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Territory.
        /// </summary>
        public static string CurrentTerritory {
            get {
                return ResourceManager.GetString("CurrentTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Door.
        /// </summary>
        public static string DeleteModalDescription {
            get {
                return ResourceManager.GetString("DeleteModalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Door.
        /// </summary>
        public static string DeleteModalTitle {
            get {
                return ResourceManager.GetString("DeleteModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address is outside the boundaries of the territory..
        /// </summary>
        public static string GeoCodeError1 {
            get {
                return ResourceManager.GetString("GeoCodeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine address location. Geolocation invalid..
        /// </summary>
        public static string GeoCodeError2 {
            get {
                return ResourceManager.GetString("GeoCodeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find address. Reason.
        /// </summary>
        public static string GeoCodeError3 {
            get {
                return ResourceManager.GetString("GeoCodeError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Adding more info..
        /// </summary>
        public static string GeoCodeError4 {
            get {
                return ResourceManager.GetString("GeoCodeError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Found.
        /// </summary>
        public static string GeoCodeMsg1 {
            get {
                return ResourceManager.GetString("GeoCodeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red highlights indicate that the address is outside of the territory bounds.
        /// </summary>
        public static string IndicatorMessage {
            get {
                return ResourceManager.GetString("IndicatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Changes..
        /// </summary>
        public static string ModifyModalChangeSavedErrMsg {
            get {
                return ResourceManager.GetString("ModifyModalChangeSavedErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved..
        /// </summary>
        public static string ModifyModalChangeSavedMsg {
            get {
                return ResourceManager.GetString("ModifyModalChangeSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Door.
        /// </summary>
        public static string ModifyModalDeleteDoorBtn {
            get {
                return ResourceManager.GetString("ModifyModalDeleteDoorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ModifyModalNextBtn {
            get {
                return ResourceManager.GetString("ModifyModalNextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ModifyModalPreviousBtn {
            get {
                return ResourceManager.GetString("ModifyModalPreviousBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ModifyModalSaveChanges {
            get {
                return ResourceManager.GetString("ModifyModalSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Address on Map.
        /// </summary>
        public static string ModifyModalShowMapBtn {
            get {
                return ResourceManager.GetString("ModifyModalShowMapBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Address Information.
        /// </summary>
        public static string ModifyModalTitle {
            get {
                return ResourceManager.GetString("ModifyModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity Sort.
        /// </summary>
        public static string ProximitySortBtn {
            get {
                return ResourceManager.GetString("ProximitySortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order doors by how close they are on the map..
        /// </summary>
        public static string ProximitySortBtnTitle {
            get {
                return ResourceManager.GetString("ProximitySortBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Details.
        /// </summary>
        public static string TerritoryDetailsBtn {
            get {
                return ResourceManager.GetString("TerritoryDetailsBtn", resourceCulture);
            }
        }
    }
}
