//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Territory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritoryWeb.Resources.Views.Territory.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckInBtn {
            get {
                return ResourceManager.GetString("CheckInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In Territory.
        /// </summary>
        public static string CheckInModalLabel {
            get {
                return ResourceManager.GetString("CheckInModalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check-in this territory?.
        /// </summary>
        public static string CheckInModalMessage {
            get {
                return ResourceManager.GetString("CheckInModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOutBtn {
            get {
                return ResourceManager.GetString("CheckOutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Territory.
        /// </summary>
        public static string CheckOutModalAssignBtn {
            get {
                return ResourceManager.GetString("CheckOutModalAssignBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Territory.
        /// </summary>
        public static string CheckOutModalLabel {
            get {
                return ResourceManager.GetString("CheckOutModalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the person you want to assign this territory to.
        /// </summary>
        public static string CheckOutModalMessage {
            get {
                return ResourceManager.GetString("CheckOutModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Door List.
        /// </summary>
        public static string DoorListButton {
            get {
                return ResourceManager.GetString("DoorListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors Details.
        /// </summary>
        public static string DoorsDetails {
            get {
                return ResourceManager.GetString("DoorsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Territory.
        /// </summary>
        public static string EditTerritoryBtn {
            get {
                return ResourceManager.GetString("EditTerritoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to check out territory.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Territory.
        /// </summary>
        public static string PrintTerritoryBtn {
            get {
                return ResourceManager.GetString("PrintTerritoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Territory Detailed.
        /// </summary>
        public static string PrintTerritoryDetailsBtn {
            get {
                return ResourceManager.GetString("PrintTerritoryDetailsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Territory (Proximity Sort).
        /// </summary>
        public static string PrintTerritoryProxBtn {
            get {
                return ResourceManager.GetString("PrintTerritoryProxBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory View.
        /// </summary>
        public static string TerritoryViewLabel {
            get {
                return ResourceManager.GetString("TerritoryViewLabel", resourceCulture);
            }
        }
    }
}
