//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerritoryWebEntities : DbContext
    {
        public TerritoryWebEntities()
            : base("name=TerritoryWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Congregation> Congregations { get; set; }
        public virtual DbSet<DoorCode> DoorCodes { get; set; }
        public virtual DbSet<TerritoryType> TerritoryTypes { get; set; }
        public virtual DbSet<TerritoryBound> TerritoryBounds { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<PublisherType> PublisherTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<Door> Doors { get; set; }
        public virtual DbSet<URLMinimizeStore> URLMinimizeStores { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
    }
}
