//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryBound
    {
        public int BoundaryID { get; set; }
        public int TerritoryID { get; set; }
        public decimal GeoLat { get; set; }
        public decimal GeoLong { get; set; }
    
        public virtual Territory Territory { get; set; }
    }
}
