//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Territory()
        {
            this.TerritoryBounds = new HashSet<TerritoryBound>();
            this.Doors = new HashSet<Door>();
        }
    
        public int Id { get; set; }
        public string TerritoryName { get; set; }
        public string City { get; set; }
        public int Type { get; set; }
        public string Notes { get; set; }
        public int CongregationID { get; set; }
        public string AssignedPublisherID { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime Added { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<System.DateTime> CheckedOut { get; set; }
        public Nullable<System.DateTime> CheckedIn { get; set; }
        public string LastCheckedInBy { get; set; }
    
        public virtual Congregation Congregation { get; set; }
        public virtual TerritoryType TerritoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerritoryBound> TerritoryBounds { get; set; }
        public virtual AspNetUser AssignedUser { get; set; }
        public virtual AspNetUser LastCheckedInUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Door> Doors { get; set; }
    }
}
