//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritoryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLMinimizeStore
    {
        public int id { get; set; }
        public string shortURL { get; set; }
        public string longURL { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> used { get; set; }
    }
}
